### ISSUE TITLE
Consider adding PHPStan package inside require-dev block on composer.json

### ISSUE THREAD

**Issue by peter279k** [bovigo/assert#14]
As title, to let developers do static code on development environment, it should be nice to define PHPStan package inside `require-dev` block on `composer.json` file.

Once this issue is accepted by repository owner, I'll be happy to work on this.

**Comment by mikey179** [comment]
In the past I was against that, as I don't like having a tool as a dependency, I believe dependencies should be actual code related dependencies only. However, as PHPStan doesn't seem to bring a lot of baggage (i.e. even more dependencies) I decided to break my personal rule and add it.
